# This workflow will run a zip command on the apps contents and uplad it as an artifact

name: Zip app contents

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.10.12
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Zip the Package
      run: |
        zip -r package.zip function_app.py requirements.txt host.json
     
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./package.zip
        asset_name: package.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
