# This workflow will run a zip command on the apps contents and uplad it as an artifact

name: Zip app contents

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.10.12
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Zip the Package
      run: |
        zip -r package.zip function_app.py requirements.txt host.json
     
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: zip-artifact
        path: package.zip
